<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Proveedor', 'doctrine');

/**
 * BaseProveedor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $razon_social
 * @property string $nit
 * @property Doctrine_Collection $Evento
 * @property Doctrine_Collection $PagoProveedor
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getRazonSocial()   Returns the current record's "razon_social" value
 * @method string              getNit()           Returns the current record's "nit" value
 * @method Doctrine_Collection getEvento()        Returns the current record's "Evento" collection
 * @method Doctrine_Collection getPagoProveedor() Returns the current record's "PagoProveedor" collection
 * @method Proveedor           setId()            Sets the current record's "id" value
 * @method Proveedor           setRazonSocial()   Sets the current record's "razon_social" value
 * @method Proveedor           setNit()           Sets the current record's "nit" value
 * @method Proveedor           setEvento()        Sets the current record's "Evento" collection
 * @method Proveedor           setPagoProveedor() Sets the current record's "PagoProveedor" collection
 * 
 * @package    coopeud
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProveedor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('proveedor');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('razon_social', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('nit', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Evento', array(
             'local' => 'id',
             'foreign' => 'proveedor_id'));

        $this->hasMany('PagoProveedor', array(
             'local' => 'id',
             'foreign' => 'proveedor_id'));
    }
}