<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RolPermiso', 'doctrine');

/**
 * BaseRolPermiso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $rol_id
 * @property integer $permiso_id
 * @property Permiso $Permiso
 * @property Rol $Rol
 * 
 * @method integer    getId()         Returns the current record's "id" value
 * @method integer    getRolId()      Returns the current record's "rol_id" value
 * @method integer    getPermisoId()  Returns the current record's "permiso_id" value
 * @method Permiso    getPermiso()    Returns the current record's "Permiso" value
 * @method Rol        getRol()        Returns the current record's "Rol" value
 * @method RolPermiso setId()         Sets the current record's "id" value
 * @method RolPermiso setRolId()      Sets the current record's "rol_id" value
 * @method RolPermiso setPermisoId()  Sets the current record's "permiso_id" value
 * @method RolPermiso setPermiso()    Sets the current record's "Permiso" value
 * @method RolPermiso setRol()        Sets the current record's "Rol" value
 * 
 * @package    coopeud
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRolPermiso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rol_permiso');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('rol_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('permiso_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Permiso', array(
             'local' => 'permiso_id',
             'foreign' => 'id'));

        $this->hasOne('Rol', array(
             'local' => 'rol_id',
             'foreign' => 'id'));
    }
}