<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PagoProveedor', 'doctrine');

/**
 * BasePagoProveedor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $evento_id
 * @property date $fecha_pago
 * @property integer $proveedor_id
 * @property Evento $Evento
 * @property Proveedor $Proveedor
 * 
 * @method integer       getId()           Returns the current record's "id" value
 * @method integer       getEventoId()     Returns the current record's "evento_id" value
 * @method date          getFechaPago()    Returns the current record's "fecha_pago" value
 * @method integer       getProveedorId()  Returns the current record's "proveedor_id" value
 * @method Evento        getEvento()       Returns the current record's "Evento" value
 * @method Proveedor     getProveedor()    Returns the current record's "Proveedor" value
 * @method PagoProveedor setId()           Sets the current record's "id" value
 * @method PagoProveedor setEventoId()     Sets the current record's "evento_id" value
 * @method PagoProveedor setFechaPago()    Sets the current record's "fecha_pago" value
 * @method PagoProveedor setProveedorId()  Sets the current record's "proveedor_id" value
 * @method PagoProveedor setEvento()       Sets the current record's "Evento" value
 * @method PagoProveedor setProveedor()    Sets the current record's "Proveedor" value
 * 
 * @package    coopeud
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePagoProveedor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pago_proveedor');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('evento_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_pago', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('proveedor_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Evento', array(
             'local' => 'evento_id',
             'foreign' => 'id'));

        $this->hasOne('Proveedor', array(
             'local' => 'proveedor_id',
             'foreign' => 'id'));
    }
}