<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DetalleInscripcion', 'doctrine');

/**
 * BaseDetalleInscripcion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $inscripcion_id
 * @property integer $persona_id
 * @property integer $coopago
 * @property Inscripcion $Inscripcion
 * @property Afiliado $Afiliado
 * 
 * @method integer            getId()             Returns the current record's "id" value
 * @method integer            getInscripcionId()  Returns the current record's "inscripcion_id" value
 * @method integer            getPersonaId()      Returns the current record's "persona_id" value
 * @method integer            getCoopago()        Returns the current record's "coopago" value
 * @method Inscripcion        getInscripcion()    Returns the current record's "Inscripcion" value
 * @method Afiliado           getAfiliado()       Returns the current record's "Afiliado" value
 * @method DetalleInscripcion setId()             Sets the current record's "id" value
 * @method DetalleInscripcion setInscripcionId()  Sets the current record's "inscripcion_id" value
 * @method DetalleInscripcion setPersonaId()      Sets the current record's "persona_id" value
 * @method DetalleInscripcion setCoopago()        Sets the current record's "coopago" value
 * @method DetalleInscripcion setInscripcion()    Sets the current record's "Inscripcion" value
 * @method DetalleInscripcion setAfiliado()       Sets the current record's "Afiliado" value
 * 
 * @package    coopeud
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDetalleInscripcion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('detalle_inscripcion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('inscripcion_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('persona_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('coopago', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Inscripcion', array(
             'local' => 'inscripcion_id',
             'foreign' => 'id'));

        $this->hasOne('Afiliado', array(
             'local' => 'persona_id',
             'foreign' => 'id'));
    }
}