<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Rol', 'doctrine');

/**
 * BaseRol
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property Doctrine_Collection $RolPermiso
 * @property Doctrine_Collection $RolUsuario
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getNombre()     Returns the current record's "nombre" value
 * @method Doctrine_Collection getRolPermiso() Returns the current record's "RolPermiso" collection
 * @method Doctrine_Collection getRolUsuario() Returns the current record's "RolUsuario" collection
 * @method Rol                 setId()         Sets the current record's "id" value
 * @method Rol                 setNombre()     Sets the current record's "nombre" value
 * @method Rol                 setRolPermiso() Sets the current record's "RolPermiso" collection
 * @method Rol                 setRolUsuario() Sets the current record's "RolUsuario" collection
 * 
 * @package    coopeud
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRol extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rol');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('RolPermiso', array(
             'local' => 'id',
             'foreign' => 'rol_id'));

        $this->hasMany('RolUsuario', array(
             'local' => 'id',
             'foreign' => 'rol_id'));
    }
}