<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Asociado', 'doctrine');

/**
 * BaseAsociado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $afiliado_id
 * @property Afiliado $Afiliado
 * @property Doctrine_Collection $Beneficiario
 * @property Doctrine_Collection $Inscripcion
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method integer             getAfiliadoId()   Returns the current record's "afiliado_id" value
 * @method Afiliado            getAfiliado()     Returns the current record's "Afiliado" value
 * @method Doctrine_Collection getBeneficiario() Returns the current record's "Beneficiario" collection
 * @method Doctrine_Collection getInscripcion()  Returns the current record's "Inscripcion" collection
 * @method Asociado            setId()           Sets the current record's "id" value
 * @method Asociado            setAfiliadoId()   Sets the current record's "afiliado_id" value
 * @method Asociado            setAfiliado()     Sets the current record's "Afiliado" value
 * @method Asociado            setBeneficiario() Sets the current record's "Beneficiario" collection
 * @method Asociado            setInscripcion()  Sets the current record's "Inscripcion" collection
 * 
 * @package    coopeud
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAsociado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asociado');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('afiliado_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Afiliado', array(
             'local' => 'afiliado_id',
             'foreign' => 'id'));

        $this->hasMany('Beneficiario', array(
             'local' => 'id',
             'foreign' => 'asociado_id'));

        $this->hasMany('Inscripcion', array(
             'local' => 'id',
             'foreign' => 'asociado_id'));
    }
}