<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Funcionario', 'doctrine');

/**
 * BaseFuncionario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $persona_id
 * @property date $fecha_ingreso
 * @property Persona $Persona
 * 
 * @method integer     getId()            Returns the current record's "id" value
 * @method integer     getPersonaId()     Returns the current record's "persona_id" value
 * @method date        getFechaIngreso()  Returns the current record's "fecha_ingreso" value
 * @method Persona     getPersona()       Returns the current record's "Persona" value
 * @method Funcionario setId()            Sets the current record's "id" value
 * @method Funcionario setPersonaId()     Sets the current record's "persona_id" value
 * @method Funcionario setFechaIngreso()  Sets the current record's "fecha_ingreso" value
 * @method Funcionario setPersona()       Sets the current record's "Persona" value
 * 
 * @package    coopeud
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFuncionario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('funcionario');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('persona_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_ingreso', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Persona', array(
             'local' => 'persona_id',
             'foreign' => 'id'));
    }
}