<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Afiliado', 'doctrine');

/**
 * BaseAfiliado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $persona_id
 * @property date $fecha_afiliacion
 * @property integer $tipo
 * @property Persona $Persona
 * @property Doctrine_Collection $Asociado
 * @property Doctrine_Collection $Beneficiario
 * @property Doctrine_Collection $DetalleInscripcion
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method integer             getPersonaId()          Returns the current record's "persona_id" value
 * @method date                getFechaAfiliacion()    Returns the current record's "fecha_afiliacion" value
 * @method integer             getTipo()               Returns the current record's "tipo" value
 * @method Persona             getPersona()            Returns the current record's "Persona" value
 * @method Doctrine_Collection getAsociado()           Returns the current record's "Asociado" collection
 * @method Doctrine_Collection getBeneficiario()       Returns the current record's "Beneficiario" collection
 * @method Doctrine_Collection getDetalleInscripcion() Returns the current record's "DetalleInscripcion" collection
 * @method Afiliado            setId()                 Sets the current record's "id" value
 * @method Afiliado            setPersonaId()          Sets the current record's "persona_id" value
 * @method Afiliado            setFechaAfiliacion()    Sets the current record's "fecha_afiliacion" value
 * @method Afiliado            setTipo()               Sets the current record's "tipo" value
 * @method Afiliado            setPersona()            Sets the current record's "Persona" value
 * @method Afiliado            setAsociado()           Sets the current record's "Asociado" collection
 * @method Afiliado            setBeneficiario()       Sets the current record's "Beneficiario" collection
 * @method Afiliado            setDetalleInscripcion() Sets the current record's "DetalleInscripcion" collection
 * 
 * @package    coopeud
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAfiliado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('afiliado');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('persona_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_afiliacion', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('tipo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Persona', array(
             'local' => 'persona_id',
             'foreign' => 'id'));

        $this->hasMany('Asociado', array(
             'local' => 'id',
             'foreign' => 'afiliado_id'));

        $this->hasMany('Beneficiario', array(
             'local' => 'id',
             'foreign' => 'afiliado_id'));

        $this->hasMany('DetalleInscripcion', array(
             'local' => 'id',
             'foreign' => 'persona_id'));
    }
}