<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Beneficiario', 'doctrine');

/**
 * BaseBeneficiario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $asociado_id
 * @property integer $afiliado_id
 * @property string $parentesco
 * @property Afiliado $Afiliado
 * @property Asociado $Asociado
 * 
 * @method integer      getId()          Returns the current record's "id" value
 * @method integer      getAsociadoId()  Returns the current record's "asociado_id" value
 * @method integer      getAfiliadoId()  Returns the current record's "afiliado_id" value
 * @method string       getParentesco()  Returns the current record's "parentesco" value
 * @method Afiliado     getAfiliado()    Returns the current record's "Afiliado" value
 * @method Asociado     getAsociado()    Returns the current record's "Asociado" value
 * @method Beneficiario setId()          Sets the current record's "id" value
 * @method Beneficiario setAsociadoId()  Sets the current record's "asociado_id" value
 * @method Beneficiario setAfiliadoId()  Sets the current record's "afiliado_id" value
 * @method Beneficiario setParentesco()  Sets the current record's "parentesco" value
 * @method Beneficiario setAfiliado()    Sets the current record's "Afiliado" value
 * @method Beneficiario setAsociado()    Sets the current record's "Asociado" value
 * 
 * @package    coopeud
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBeneficiario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('beneficiario');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('asociado_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('afiliado_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parentesco', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Afiliado', array(
             'local' => 'afiliado_id',
             'foreign' => 'id'));

        $this->hasOne('Asociado', array(
             'local' => 'asociado_id',
             'foreign' => 'id'));
    }
}