<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/11/03 01:09:04

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=coopeud',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
