<?php

/**
 * AsociadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AsociadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AsociadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Asociado');
    }
}