<?php

/**
 * BeneficiarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BeneficiarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BeneficiarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Beneficiario');
    }
}