<?php

/**
 * FuncionarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FuncionarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FuncionarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Funcionario');
    }
}