<?php

/**
 * InscripcionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InscripcionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InscripcionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Inscripcion');
    }
}