<?php

/**
 * PagoInscripcionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PagoInscripcionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PagoInscripcionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PagoInscripcion');
    }
}