<?php

/**
 * PagoProveedorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PagoProveedorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PagoProveedorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PagoProveedor');
    }
}