<?php

/**
 * RolPermisoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RolPermisoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RolPermisoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RolPermiso');
    }
}