<?php

/**
 * RolUsuarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RolUsuarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RolUsuarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RolUsuario');
    }
}