<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/11/26 04:38:41

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=eventos_coopeud',
  'username' => 'coopeud',
  'password' => 'coopeud',
  'name' => 'doctrine',
)),);
