<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/11/26 04:38:41
$this->security = array (
  'index' => 
  array (
    'is_secure' => false,
  ),
  'validar' => 
  array (
    'is_secure' => false,
  ),
  'cambioclave' => 
  array (
    'is_secure' => 'on',
  ),
  'enconstruccion' => 
  array (
    'is_secure' => false,
  ),
  'error404' => 
  array (
    'is_secure' => false,
  ),
  'erroreliminacion' => 
  array (
    'is_secure' => false,
  ),
  'authenticated' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
